In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
data=pd.read_csv('train.csv',usecols=['X0','X1','X2','X3','X4','X5'])
data.head()

   X0 X1  X2 X3 X4 X5
0   k  v  at  a  d  u
1   k  t  av  e  d  y
2  az  w   n  c  d  x
3  az  t   n  f  d  x
4  az  v   n  f  d  h

In [6]:
data.shape

(4209, 6)

In [8]:
# to check the how many unique labels have each variable
for col in data.columns:
    print(col, ':', len(data[col].unique()),'labels')

X0 : 47 labels
X1 : 27 labels
X2 : 44 labels
X3 : 7 labels
X4 : 4 labels
X5 : 29 labels

In [9]:
# let's check how many columns we will obtain after one hot encoding of these variable
pd.get_dummies(data,drop_first=True).shape

(4209, 152)

In [11]:
data.X1.value_counts().sort_values(ascending=False).head(20)

aa    833
s     598
b     592
l     590
v     408
r     251
i     203
a     143
c     121
o      82
w      52
z      46
u      37
e      33
m      32
t      31
h      29
f      23
y      23
j      22
Name: X1, dtype: int64

In [12]:
# let's makes a list with most frequent categories of the variable

top_10=[x for x in data.X1.value_counts().sort_values(ascending=False).head(10).index]

In [13]:
top_10

['aa', 's', 'b', 'l', 'v', 'r', 'i', 'a', 'c', 'o']

In [16]:
# now make the 10 binary variable
for label in top_10:
    data[label]=np.where(data['X1']==label,1,0)
data[['X1']+top_10].head(40)

    X1  aa  s  b  l  v  r  i  a  c  o
0    v   0  0  0  0  1  0  0  0  0  0
1    t   0  0  0  0  0  0  0  0  0  0
2    w   0  0  0  0  0  0  0  0  0  0
3    t   0  0  0  0  0  0  0  0  0  0
4    v   0  0  0  0  1  0  0  0  0  0
5    b   0  0  1  0  0  0  0  0  0  0
6    r   0  0  0  0  0  1  0  0  0  0
7    l   0  0  0  1  0  0  0  0  0  0
8    s   0  1  0  0  0  0  0  0  0  0
9    b   0  0  1  0  0  0  0  0  0  0
10   r   0  0  0  0  0  1  0  0  0  0
11   r   0  0  0  0  0  1  0  0  0  0
12   b   0  0  1  0  0  0  0  0  0  0
13   r   0  0  0  0  0  1  0  0  0  0
14   s   0  1  0  0  0  0  0  0  0  0
15   l   0  0  0  1  0  0  0  0  0  0
16   r   0  0  0  0  0  1  0  0  0  0
17  aa   1  0  0  0  0  0  0  0  0  0
18   c   0  0  0  0  0  0  0  0  1  0
19   a   0  0  0  0  0  0  0  1  0  0
20   s   0  1  0  0  0  0  0  0  0  0
21  aa   1  0  0  0  0  0  0  0  0  0
22   r   0  0  0  0  0  1  0  0  0  0
23   b   0  0  1  0  0  0  0  0  0  0
24   r   0  0  0  0  0  1  0  0  0  0
25   s   0  1  0  0  0  0  0  0  0  0
26   l   0  0  0  1  0  0  0  0  0  0
27  aa   1  0  0  0  0  0  0  0  0  0
28   s   0  1  0  0  0  0  0  0  0  0
29   b   0  0  1  0  0  0  0  0  0  0
30   v   0  0  0  0  1  0  0  0  0  0
31   e   0  0  0  0  0  0  0  0  0  0
32   b   0  0  1  0  0  0  0  0  0  0
33   s   0  1  0  0  0  0  0  0  0  0
34   s   0  1  0  0  0  0  0  0  0  0
35   b   0  0  1  0  0  0  0  0  0  0
36   l   0  0  0  1  0  0  0  0  0  0
37   v   0  0  0  0  1  0  0  0  0  0
38   v   0  0  0  0  1  0  0  0  0  0
39   s   0  1  0  0  0  0  0  0  0  0

In [21]:
# get whole set of dummy variables ,for all the catogorical variables
def one_hot_top_x(df,variable, top_x_lebel):
    for lebel in top_x_lebel:
        df[variable+'_'+lebel]=np.where(df[variable]==lebel,1,0)
data=pd.read_csv('train.csv',usecols=['X0','X1','X2','X3','X4','X5'])    
one_hot_top_x(data,'X2',top_10)
data.head()

,X0,X1,X2,X3,X4,X5,X2_aa,X2_s,X2_b,X2_l,X2_v,X2_r,X2_i,X2_a,X2_c,X2_o
0,k,v,at,a,d,u,0,0,0,0,0,0,0,0,0,0
1,k,t,av,e,d,y,0,0,0,0,0,0,0,0,0,0
2,az,w,n,c,d,x,0,0,0,0,0,0,0,0,0,0
3,az,t,n,f,d,x,0,0,0,0,0,0,0,0,0,0
4,az,v,n,f,d,h,0,0,0,0,0,0,0,0,0,0